plugins {
    id 'java'
    id 'maven-publish' 
}

group = 'com.github.Kaique-Sique' 
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://frcmaven.wpi.edu/release' }
}

dependencies {
    implementation 'edu.wpi.first.ntcore:ntcore-java:2025.+'
    implementation 'edu.wpi.first.wpilibj:wpilibj2-java:2025.+'
}

// gera o jar da biblioteca
publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}